## YAML Template.
---

spring:
    application:
        name: user-service
    cloud:
        config:
            uri: http://localhost:8888
            token: roottoken  
   
            
server:
    port: 9888
        
#-------------------------------------------------------------------------------      
#ADDITIONAL


#-------------------------------------------------------------------------------
#GIT-CONFIG

#spring.config.import=optional:configserver:http://myconfigserver.com
#spring.cloud.config.import-check.enabled=false.

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
    

